# Generated by Django 3.1.5 on 2021-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/%Y/%M')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
