# Generated by Django 3.1.5 on 2021-02-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210215_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupload',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('lost', 'lost'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
