# Generated by Django 3.1.5 on 2021-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210218_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
