# Generated by Django 3.1.5 on 2021-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
