# Generated by Django 3.1.5 on 2021-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20210320_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesiton',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
