# Generated by Django 3.1.5 on 2021-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_signupchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='books_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signupchoice',
            name='selection',
            field=models.CharField(choices=[('I would like to upload 3 books and pay Rs. 200', 'I would like to upload 3 books and pay Rs. 200'), ('I would like to deposit Rs. 1000 and pay Rs. 200', 'I would like to deposit Rs. 1000 and pay Rs. 200')], max_length=256),
        ),
    ]
