# Generated by Django 3.1.5 on 2021-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('ad_type', models.CharField(choices=[('Hero', 'Hero'), ('HE', 'HE'), ('HL', 'Home Left'), ('HR', 'Home Right')], max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
