# Generated by Django 3.1.5 on 2021-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
