# Generated by Django 3.1.5 on 2021-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_type',
            field=models.CharField(choices=[('Hero', 'Hero'), ('HeroFooter', 'HeroFooter'), ('Home Left', 'Home Left'), ('Home Right', 'Home Right')], max_length=256),
        ),
    ]
